apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hn6qfy44w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hn6qfy44w-python 
  name: hn6qfy44w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hn6qfy44w-python 
