apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hn6qfy44w-python 
  janus-idp.io/tekton: hn6qfy44w-python
  backstage.io/kubernetes-id: hn6qfy44w-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hn6qfy44w-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  